### ISSUE TITLE
Template not working

### ISSUE THREAD

**Issue by Nrosa01** [animotionjs/animotion#21]
I initliazed a project using the npx command and also downloading the template in this repo. I run pnpm i and pnpm run dev. But I get this error from a svelte plugin

```cmd
failed to load config from C:\Users\Usuario\Downloads\animotionjs animotion main packages-create_template\vite.config.ts
error when starting dev server:
file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@2.5.3_svelte@4.2.10_vite@4.5.2/node_modules/@sveltejs/vite-plugin-svelte/src/index.js:5
import { svelteInspector } from '@sveltejs/vite-plugin-svelte-inspector';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'svelteInspector' not found. The requested module '@sveltejs/vite-plugin-svelte-inspector' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sveltejs/vite-plugin-svelte-inspector';
const { svelteInspector } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadConfigFromBundledFile (file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/vite@4.5.2_@types+node@20.11.17/node_modules/vite/dist/node/chunks/dep-52909643.js:66332:21)
    at async loadConfigFromFile (file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/vite@4.5.2_@types+node@20.11.17/node_modules/vite/dist/node/chunks/dep-52909643.js:66181:28)
    at async resolveConfig (file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/vite@4.5.2_@types+node@20.11.17/node_modules/vite/dist/node/chunks/dep-52909643.js:65777:28)
    at async _createServer (file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/vite@4.5.2_@types+node@20.11.17/node_modules/vite/dist/node/chunks/dep-52909643.js:65051:20)
    at async CAC.<anonymous> (file:///C:/Users/Usuario/Downloads/animotionjs%20animotion%20main%20packages-create_template/node_modules/.pnpm/vite@4.5.2_@types+node@20.11.17/node_modules/vite/dist/node/cli.js:763:24)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by mattcroat** [comment]
Can you provide a reproduction? 😄

**Comment by Nrosa01** [comment]
Uhhh sorry but I don't think I can. I did what I said. But I've tried in another machine and it worked so now I'm not sure if I'm missing a dep or something. I have pnpm installed through volta. I'll return to this issue when I find what's exactly happening. I did nothing but trying to run the animotion template

**Comment by Nrosa01** [comment]
Well, it seems that it was because tsc wasn't installed or wasn't in my PATH. I'm not sure but after running npm install --global typescript it works
