### ISSUE TITLE
Error on initial load

### ISSUE THREAD

**Issue by Rambatino** [animotionjs/animotion#49]
> npx
> create

┌  Welcome to Animotion!
│
◇  Where should I create your project?
│  (press Enter to use the current directory)
│
◇  Directory not empty. Continue?
│  Yes
│
◇  Pick the template you want to use:
│  File-based slides
│
◇  Install dependencies? (requires pnpm)
│  Yes
│
◇  Installed dependencies.
│
└  Done. 🪄

💿️ Start the development server:
pnpm run dev

💬 Discord
https://joyofcode.xyz/invite
➜  episode1 pnpm run dev

> animotion@ dev /Users/axiom/youtube/episode1
> vite dev

13:00:38 [vite-plugin-svelte] You are using Svelte 5.0.0-next.167. Svelte 5 support is experimental, breaking changes can occur in any release until this notice is removed.
work in progress:
 - svelte-inspector is disabled until dev mode implements node to code mapping

Forced re-optimization of dependencies

  VITE v5.2.11  ready in 959 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
13:00:42 [vite] Pre-transform error: [postcss] Missing "./theme" specifier in "@animotion/core" package
13:00:42 [vite] Error when evaluating SSR module /src/routes/+layout.svelte: failed to import "/src/styles/app.css"
|- Error: [postcss] Missing "./theme" specifier in "@animotion/core" package
    at e (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:25)
    at n (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:627)
    at o (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47597:1297)
    at resolveExportsOrImports (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48287:20)
    at resolveDeepImport (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48306:31)
    at tryNodeResolve (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
    at Context.resolveId (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
    at Object.resolveId (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
    at async Object.<anonymous> (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68310:21)
    at async Object.resolve (file://node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:32205:34)

**Comment by Rambatino** [comment]
Running:

```
pnpm update --latest 
pnpm add tailwindcss@next @tailwindcss/vite@next
```
fixes it :)
